AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'tempus.gemspec'
    - 'spec/**/*.rb'

Layout/LineLength:
  Exclude:
    - 'tempus.gemspec'

Style/RedundantRegexpEscape:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false